import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Terminal as TerminalIcon, 
  Send, 
  ShieldAlert, 
  Zap, 
  Check, 
  Bot, 
  User as UserIcon,
  CheckCircle2,
  AlertTriangle,
  X,
  CornerDownLeft,
  Copy,
  Brain,
  ChevronDown,
  ChevronUp,
  Sparkles,
  Loader2,
  Activity,
  Trash2,
  Share2,
  FileCode
} from 'lucide-react';
import { Incident } from '../types';
import { startIncident, approveFix, rejectFix } from '../services/api';
import { DiffViewer } from '../components/DiffViewer';
import { TerminalConsole } from '../components/TerminalConsole';

interface CommandCenterProps {
  incidents: Incident[];
  onRefreshIncidents: () => void;
}

export const CommandCenter: React.FC<CommandCenterProps> = ({ incidents, onRefreshIncidents }) => {
  const [promptText, setPromptText] = useState<string>('');
  const [selectedScenarioKey, setSelectedScenarioKey] = useState<string>('DATABASE_STOPPED');
  const [activeIncidentId, setActiveIncidentId] = useState<string | null>(null);
  const [showTerminalModal, setShowTerminalModal] = useState<boolean>(false);
  const [isInvestigating, setIsInvestigating] = useState<boolean>(false);
  const [showReasoningTimeline, setShowReasoningTimeline] = useState<boolean>(false);
  const [showDiffDetails, setShowDiffDetails] = useState<boolean>(false);
  const [copiedPrompt, setCopiedPrompt] = useState<boolean>(false);
  const [copiedSlackReport, setCopiedSlackReport] = useState<boolean>(false);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (incidents.length > 0 && !activeIncidentId) {
      setActiveIncidentId(incidents[0].id);
    }
  }, [incidents, activeIncidentId]);

  const activeIncident = incidents.find(i => i.id === activeIncidentId) || incidents[0];

  // Dynamic real calculation from SQLite DB timestamps and event items
  const stepCount = activeIncident?.events?.length || 4;
  const startTime = activeIncident ? new Date(activeIncident.startedAt).getTime() : Date.now();
  const lastEventTime = activeIncident?.events && activeIncident.events.length > 0
    ? new Date(activeIncident.events[activeIncident.events.length - 1].createdAt).getTime()
    : startTime + 2100;
  const durationSec = Math.max(0.8, ((lastEventTime - startTime) / 1000)).toFixed(1);

  const handleLaunchInvestigation = async () => {
    const textToSend = promptText.trim() || 'Meri production API down hai, 502 Bad Gateway aa raha hai. Root cause trace karke fix karo.';
    try {
      setIsInvestigating(true);
      const newInc = await startIncident(textToSend, selectedScenarioKey);
      setActiveIncidentId(newInc.id);
      setPromptText('');
      onRefreshIncidents();
    } catch (err) {
      console.error(err);
    } finally {
      setIsInvestigating(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleLaunchInvestigation();
    }
  };

  const handleApprove = async (approvalId: string) => {
    try {
      await approveFix(approvalId);
      onRefreshIncidents();
    } catch (err) {
      console.error(err);
    }
  };

  const handleReject = async (approvalId: string) => {
    try {
      await rejectFix(approvalId);
      onRefreshIncidents();
    } catch (err) {
      console.error(err);
    }
  };

  const handleCopyPrompt = () => {
    if (activeIncident?.userPrompt) {
      navigator.clipboard.writeText(activeIncident.userPrompt);
      setCopiedPrompt(true);
      setTimeout(() => setCopiedPrompt(false), 2000);
    }
  };

  const handleCopySlackReport = () => {
    if (activeIncident) {
      const report = `🚨 *OpsPilot Incident Report: #${activeIncident.id}*\n` +
        `*Title:* ${activeIncident.title}\n` +
        `*Severity:* ${activeIncident.severity}\n` +
        `*Status:* ${activeIncident.status}\n` +
        `*Root Cause:* ${activeIncident.rootCause || 'Under Investigation'} (Confidence: ${activeIncident.confidence}%)\n` +
        (activeIncident.activeApproval ? `*Proposed Fix:* ${activeIncident.activeApproval.title}\n` : '') +
        `\n_Generated by OpsPilot AI Agent_`;
      navigator.clipboard.writeText(report);
      setCopiedSlackReport(true);
      setTimeout(() => setCopiedSlackReport(false), 2000);
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }} 
      animate={{ opacity: 1, y: 0 }} 
      transition={{ duration: 0.35 }}
      className="flex flex-col gap-4 max-w-4xl mx-auto font-sans relative pb-6"
    >
      
      {/* Top Control Bar — no longer sticky since main scrolls */}
      <div className="glass-panel border theme-border rounded-xl py-3 px-4 w-full">
        <div className="flex flex-wrap items-center justify-between gap-3">
          
          {/* Left: Brand + Status */}
          <div className="flex items-center gap-2 shrink-0">
            <div className="w-7 h-7 rounded-lg bg-gradient-to-tr from-blue-600 to-indigo-600 flex items-center justify-center text-white shadow-md glow-blue shrink-0">
              <Bot className="w-4 h-4 animate-pulse" />
            </div>
            <span className="text-sm font-extrabold text-title">OpsPilot AI</span>
            <span className="hidden sm:inline-block text-[10px] font-mono px-2 py-0.5 rounded bg-blue-500/10 text-blue-400 border border-blue-500/20">
              GPT-4o
            </span>
            <div className="hidden md:flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 text-[10px] font-mono border border-emerald-500/20">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
              <span>Docker Healthy</span>
            </div>
          </div>

          {/* Right: Dropdown & Action Buttons */}
          <div className="flex items-center gap-2 shrink-0">
            <select
              value={activeIncidentId || ''}
              onChange={(e) => setActiveIncidentId(e.target.value)}
              className="theme-input px-3 py-1.5 rounded-xl border theme-border text-xs text-title font-mono focus:outline-none max-w-[180px] sm:max-w-[220px] truncate"
            >
              {incidents.map(inc => (
                <option key={inc.id} value={inc.id}>
                  #{inc.id} — {inc.title}
                </option>
              ))}
            </select>

            <motion.button
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              onClick={handleCopySlackReport}
              title="Copy Slack Report"
              className="flex items-center gap-1.5 px-2.5 py-1.5 card-bg-subtle hover:opacity-80 text-subtitle text-xs font-semibold rounded-xl border theme-border transition shrink-0"
            >
              {copiedSlackReport ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Share2 className="w-3.5 h-3.5 text-blue-400" />}
              <span className="hidden sm:inline">{copiedSlackReport ? 'Copied' : 'Report'}</span>
            </motion.button>

            <motion.button
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              onClick={() => setShowTerminalModal(true)}
              className="flex items-center gap-1.5 px-2.5 py-1.5 card-bg-subtle hover:opacity-80 text-title text-xs font-bold rounded-xl border theme-border transition shrink-0"
            >
              <TerminalIcon className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
              <span>Logs</span>
            </motion.button>
          </div>

        </div>
      </div>

      {/* Clean Linear Conversation Stream */}
      <div className="flex-1 space-y-6 py-2">
        {activeIncident ? (
          <>
            {/* USER PROMPT MESSAGE — ALIGNED CLEANLY TO THE RIGHT */}
            <motion.div 
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
              className="flex flex-row-reverse items-start gap-3 ml-auto max-w-xl"
            >
              <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-blue-600 to-indigo-600 text-white flex items-center justify-center font-bold text-xs shrink-0 shadow-md">
                You
              </div>
              <div className="theme-chat-user border p-4 rounded-2xl rounded-tr-none flex-1 space-y-1 text-right shadow-md">
                <div className="flex items-center justify-between text-[11px] text-blue-500 font-mono">
                  <button onClick={handleCopyPrompt} className="hover:text-blue-600 transition flex items-center gap-1 text-subtitle">
                    {copiedPrompt ? <Check className="w-3 h-3 text-emerald-500" /> : <Copy className="w-3 h-3 text-blue-500" />}
                    <span className="text-[10px]">{copiedPrompt ? 'Copied' : 'Copy'}</span>
                  </button>
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-title">Operator Command Prompt</span>
                    <span className="text-subtitle">[{new Date(activeIncident.startedAt).toLocaleTimeString()}]</span>
                  </div>
                </div>
                <p className="text-xs text-title font-mono leading-relaxed">
                  "{activeIncident.userPrompt}"
                </p>
              </div>
            </motion.div>

            {/* OPSPILOT AI AGENT STREAM — 3-STEP EASY TO UNDERSTAND CARD */}
            <motion.div 
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.45, delay: 0.05, ease: [0.16, 1, 0.3, 1] }}
              className="flex flex-row items-start gap-3 mr-auto max-w-2xl"
            >
              <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-purple-600 to-indigo-600 text-white flex items-center justify-center font-bold text-xs shrink-0 shadow-md glow-blue">
                <Bot className="w-4 h-4 animate-pulse" />
              </div>

              <div className="theme-chat-ai border p-5 rounded-2xl rounded-tl-none flex-1 space-y-4">
                
                {/* Reasoning Accordion Summary Line (Dynamic Real Stats) */}
                <div className="flex items-center justify-between text-xs font-mono text-subtitle theme-reasoning-bar p-2.5 rounded-xl border theme-border">
                  <div className="flex items-center gap-2">
                    <Brain className="w-4 h-4 text-purple-400 animate-pulse" />
                    <span className="text-subtitle">Thought for {durationSec}s • {stepCount} steps completed</span>
                  </div>
                  <button 
                    onClick={() => setShowReasoningTimeline(!showReasoningTimeline)}
                    className="text-blue-400 hover:underline flex items-center gap-1 font-semibold"
                  >
                    <span>{showReasoningTimeline ? 'Hide reasoning' : 'Show reasoning'}</span>
                    {showReasoningTimeline ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
                  </button>
                </div>

                {/* Collapsible Reasoning Details */}
                <AnimatePresence>
                  {showReasoningTimeline && (
                    <motion.div 
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      transition={{ duration: 0.3 }}
                      className="theme-code-block p-3.5 rounded-xl border theme-border space-y-2 text-xs font-mono text-subtitle overflow-hidden"
                    >
                      {activeIncident.events.map((evt) => (
                        <div key={evt.id} className="flex items-center gap-2">
                          <Check className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                          <span>{evt.title}</span>
                        </div>
                      ))}
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* STEP 1: PROBLEM (ROOT CAUSE DIAGNOSED) */}
                {activeIncident.rootCause && (
                  <motion.div 
                    initial={{ opacity: 0, scale: 0.98 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="border-l-4 theme-alert-cyan p-4 rounded-r-xl space-y-1 shadow-sm"
                  >
                    <div className="flex items-center justify-between text-xs text-cyan-600 font-bold">
                      <span className="flex items-center gap-1.5 uppercase tracking-wider">
                        <Zap className="w-4 h-4 text-cyan-600" /> Step 1: Root Cause Diagnosed
                      </span>
                      <span className="font-mono">Confidence: {activeIncident.confidence}%</span>
                    </div>
                    <p className="text-xs font-semibold text-title leading-relaxed pt-1">
                      {activeIncident.rootCause}
                    </p>
                  </motion.div>
                )}

                {/* STEP 2 & 3: PROPOSED FIX & 1-CLICK APPROVAL */}
                {activeIncident.status === 'AWAITING_APPROVAL' && activeIncident.activeApproval && (
                  <motion.div 
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="theme-alert-amber border border-amber-500/50 p-5 rounded-2xl space-y-4 shadow-md glow-amber"
                  >
                    <div className="flex items-center justify-between border-b theme-border pb-3">
                      <div className="flex items-center gap-2">
                        <ShieldAlert className="w-5 h-5 text-amber-400 animate-bounce" />
                        <h3 className="text-sm font-extrabold text-title">Step 2: {activeIncident.activeApproval.title}</h3>
                      </div>
                      <span className="px-2.5 py-0.5 rounded text-[11px] font-mono font-bold bg-amber-500/20 text-amber-600 border border-amber-500/40">
                        Risk: {activeIncident.activeApproval.riskLevel}
                      </span>
                    </div>

                    <p className="text-xs text-title font-medium leading-relaxed">
                      {activeIncident.activeApproval.description}
                    </p>

                    {/* Step 3 Action Buttons */}
                    <div className="flex items-center justify-between gap-3 pt-2">
                      <button
                        onClick={() => setShowDiffDetails(!showDiffDetails)}
                        className="flex items-center gap-1.5 px-3 py-2 card-bg-subtle hover:opacity-80 text-subtitle text-xs font-semibold rounded-xl border theme-border transition"
                      >
                        <FileCode className="w-3.5 h-3.5 text-blue-400" />
                        <span>{showDiffDetails ? 'Hide Diff & Commands' : 'View Diff & Commands'}</span>
                      </button>

                      <div className="flex items-center gap-2">
                        <motion.button
                          whileHover={{ scale: 1.02 }}
                          whileTap={{ scale: 0.98 }}
                          onClick={() => handleReject(activeIncident.activeApproval!.id)}
                          className="px-3.5 py-2 card-bg-subtle hover:opacity-80 text-subtitle text-xs font-bold rounded-xl border theme-border transition"
                        >
                          Reject
                        </motion.button>
                        <motion.button
                          whileHover={{ scale: 1.03 }}
                          whileTap={{ scale: 0.97 }}
                          onClick={() => handleApprove(activeIncident.activeApproval!.id)}
                          className="flex items-center gap-2 px-5 py-2 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white text-xs font-bold rounded-xl shadow-lg glow-emerald transition"
                        >
                          <Check className="w-4 h-4" />
                          <span>Approve & Execute Fix</span>
                        </motion.button>
                      </div>
                    </div>

                    {/* Optional Collapsible Diff Viewer */}
                    <AnimatePresence>
                      {showDiffDetails && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: 'auto' }}
                          exit={{ opacity: 0, height: 0 }}
                          transition={{ duration: 0.3 }}
                          className="overflow-hidden pt-2"
                        >
                          <DiffViewer
                            diffText={activeIncident.activeApproval.diff}
                            commands={activeIncident.activeApproval.commands}
                            title="Proposed Recovery Commands & Git Patch"
                          />
                        </motion.div>
                      )}
                    </AnimatePresence>

                  </motion.div>
                )}

                {/* Animated Typing Indicator */}
                {isInvestigating && (
                  <motion.div 
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex items-center gap-3 text-xs font-mono text-blue-400 card-bg-subtle p-3 rounded-xl border theme-border"
                  >
                    <Loader2 className="w-4 h-4 animate-spin text-blue-400" />
                    <span>OpsPilot AI is inspecting container logs & running OpenAI tool calls...</span>
                  </motion.div>
                )}

                {/* Resolved Banner */}
                {activeIncident.status === 'RESOLVED' && (
                  <motion.div 
                    initial={{ opacity: 0, scale: 0.98 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="border-l-4 theme-alert-emerald p-3.5 rounded-r-xl text-xs font-bold text-emerald-600 flex items-center gap-2"
                  >
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span>Incident Resolved & Service Health Verified (HTTP 200)</span>
                  </motion.div>
                )}

              </div>
            </motion.div>

            <div ref={messagesEndRef} />
          </>
        ) : (
          <div className="p-8 text-center text-subtitle text-xs">
            No incident selected. Use the Chat Editor below to start an investigation.
          </div>
        )}
      </div>

      {/* CLEAN IN-FLOW CHAT EDITOR */}
      <div>
        <div className="glass-panel p-3.5 rounded-2xl border theme-border shadow-2xl backdrop-blur-2xl space-y-2.5 focus-within:border-blue-500/80 transition-all">
          <textarea
            rows={2}
            value={promptText}
            onChange={(e) => setPromptText(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask OpsPilot to investigate an outage or fix code risks... (Press Enter to send)"
            className="w-full bg-transparent border-none text-title text-xs focus:outline-none placeholder:text-subtitle font-mono resize-none leading-relaxed px-1"
          />

          <div className="flex items-center justify-between border-t theme-border pt-2 font-mono text-xs">
            <div className="flex items-center gap-1.5 overflow-x-auto">
              {[
                { key: 'DATABASE_STOPPED', label: '⚡ 502 Outage', prompt: 'Meri production API down hai, 502 Bad Gateway aa raha hai. Root cause trace karke fix karo.' },
                { key: 'CONFIG_MISMATCH', label: '🛠 Config Mismatch', prompt: 'API DB connection error aa raha hai after deployment. Check configs.' },
                { key: 'CODE_BUG', label: '🐞 Login 500 Bug', prompt: 'Login API 500 error de rahi hai. Stack trace padh ke safe patch karo.' },
              ].map(sc => (
                <button
                  key={sc.key}
                  onClick={() => {
                    setSelectedScenarioKey(sc.key);
                    setPromptText(sc.prompt);
                  }}
                  className={`px-2.5 py-1 rounded-lg text-[10px] font-bold shrink-0 transition ${
                    selectedScenarioKey === sc.key
                      ? 'bg-blue-600/30 text-blue-400 border border-blue-500/50'
                      : 'card-bg-subtle text-subtitle border theme-border hover:text-title'
                  }`}
                >
                  {sc.label}
                </button>
              ))}
            </div>

            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={handleLaunchInvestigation}
              disabled={isInvestigating}
              className="w-8 h-8 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 disabled:opacity-50 text-white flex items-center justify-center shadow-md glow-blue transition-all cursor-pointer shrink-0"
            >
              <Send className="w-3.5 h-3.5" />
            </motion.button>
          </div>
        </div>
      </div>

      {/* Sleek Terminal Logs Modal */}
      {showTerminalModal && activeIncident && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <TerminalConsole
            events={activeIncident.events}
            incidentId={activeIncident.id}
            onClose={() => setShowTerminalModal(false)}
          />
        </div>
      )}

    </motion.div>
  );
};
